export const PRESET_CONFIGS = [
  {
    id: "pop-c",
    name: "First Pop Improv in C",
    key: "C",
    mode: "major",
    progressionPresetId: "pop-4",
    lhId: "pop-8ths",
    motifId: "pop-hook-1351",
    length: 8,
    styleId: "pop",
    anchors: {
      lh: "C3",
      rh: "C5",
      chords: {
        I: "C3",
        i: "C3",
        V: "G3",
        v: "G3",
        IV: "F3",
        iv: "F3",
        vi: "A2",
        VI: "A2",
      },
    },
  },
  {
    id: "blues-a",
    name: "12-Bar Minor Blues in A",
    key: "A",
    mode: "minorBlues",
    progressionPresetId: "blues-12-minor",
    lhId: "root-5th-oct",
    motifId: "blues-riff",
    length: 12,
    styleId: "jazz",
    anchors: {
      lh: "A2",
      rh: "E4",
      chords: {
        i: "A2",
        i7: "A2",
        I: "A2",
        I7: "A2",
        iv: "D3",
        iv7: "D3",
        IV: "D3",
        IV7: "D3",
        V: "E3",
        V7: "E3",
      },
    },
  },
  {
    id: "classical-f",
    name: "Classical Alberti in F",
    key: "F",
    mode: "major",
    progressionPresetId: "basic-cadence",
    lhId: "alberti",
    motifId: "step-arch",
    length: 8,
    styleId: "classical",
    anchors: { lh: "F3", rh: "C5" },
  },
  {
    id: "lofi-d",
    name: "Lo-Fi Minor Loop in D",
    key: "D",
    mode: "pentatonicMinor",
    progressionPresetId: "lofi-loop",
    lhId: "pedal",
    motifId: "lofi-sway",
    length: 8,
    styleId: "modal",
    anchors: {
      lh: "D2",
      rh: "E4",
      chords: {
        i: "D3",
        I: "D3",
        VI: "Bb2",
        vi: "Bb2",
        III: "F2",
        iii: "F2",
        VII: "C3",
        vii: "C3",
      },
    },
  },
  {
    id: "jazz-bb",
    name: "Jazz ii–V–I in Bb",
    key: "A#",
    mode: "major",
    progressionPresetId: "jazz-251",
    lhId: "walking",
    motifId: "swing-lick-3579",
    length: 4,
    styleId: "jazz",
    anchors: { lh: "A#2", rh: "D5" },
  },
  {
    id: "harmonic-e",
    name: "E Harmonic Minor Drama",
    key: "E",
    mode: "harmonicMinor",
    progressionPresetId: "harmonic-cadence",
    lhId: "oompah",
    motifId: "harmonic-rise",
    length: 8,
    styleId: "classical",
    anchors: { lh: "G3", rh: "A4" },
  },
  {
    id: "modal-g",
    name: "G Minor Modal Vamp",
    key: "G",
    mode: "minor",
    progressionPresetId: "modal-vamp",
    lhId: "pedal",
    motifId: "modal-pedal",
    length: 8,
    styleId: "modal",
    anchors: { lh: "G3", rh: "A4" },
  },
  {
    id: "pent-c",
    name: "Pentatonic Bootcamp in C",
    key: "C",
    mode: "pentatonicMinor",
    progressionPresetId: "pent-bootcamp",
    lhId: "block",
    motifId: "pent-grid",
    length: 4,
    styleId: "pop",
    anchors: { lh: "C3", rh: "E4" },
  },
  {
    id: "ned-shearon",
    name: "Ned Shearon (Romantic Pop)",
    key: "D",
    mode: "major",
    progressionPresetId: "pop-4",
    lhId: "pop-8ths",
    motifId: "ballad-long",
    length: 8,
    styleId: "pop",
    anchors: {
      lh: "D3",
      rh: "A4",
      chords: {
        I: "D2",
        V: "A2",
        vi: "B2",
        IV: "G2",
      },
    },
  },
  {
    id: "verde-dia",
    name: "Verde Dia (Pop Punk)",
    key: "G",
    mode: "major",
    progressionPresetId: "deceptive-cadence",
    lhId: "power-8ths",
    motifId: "pop-offbeat-echo",
    length: 8,
    styleId: "pop",
    anchors: { lh: "G2", rh: "D4" },
  },
  {
    id: "coldplayer",
    name: "Coldplayer (Emotional Arps)",
    key: "D#",
    mode: "major",
    progressionPresetId: "pop-4",
    lhId: "broken",
    motifId: "arpeggio-climb",
    length: 12,
    styleId: "modal",
    anchors: { lh: "D#3", rh: "A#4" },
  },
  {
    id: "tayla-swift",
    name: "Tayla Swift Loop (Folk Pop)",
    key: "C",
    mode: "major",
    progressionPresetId: "pop-backwards",
    lhId: "oompah",
    motifId: "step-arch",
    length: 8,
    styleId: "pop",
    anchors: { lh: "C3", rh: "E4" },
  },
  {
    id: "billie-eyelash",
    name: "Billie Eyelash Mode (Dreamy Minor)",
    key: "A",
    mode: "minor",
    progressionPresetId: "modal-lament",
    lhId: "pedal",
    motifId: "modal-pedal",
    length: 8,
    styleId: "modal",
    anchors: { lh: "A2", rh: "C4" },
  },
  {
    id: "brunho-bars",
    name: "Brunho Bars (Soul Pop)",
    key: "C",
    mode: "major",
    progressionPresetId: "doo-wop",
    lhId: "block",
    motifId: "pent-grid",
    length: 8,
    styleId: "pop",
    anchors: { lh: "C3", rh: "E4" },
  },
  {
    id: "daft-ponk",
    name: "Daft Ponk Loop (Neo-Disco)",
    key: "B",
    mode: "minor",
    progressionPresetId: "neo-disco",
    lhId: "pop-8ths",
    motifId: "funk-sync",
    length: 8,
    styleId: "pop",
    anchors: { lh: "B2", rh: "D4" },
  },
  {
    id: "john-legendairy",
    name: "John Legendairy Ballad",
    key: "F",
    mode: "minor",
    progressionPresetId: "lofi-loop",
    lhId: "alberti",
    motifId: "ballad-call-response",
    length: 8,
    styleId: "classical",
    anchors: { lh: "F3", rh: "C5" },
  },
];

export const DEFAULT_PRESET_ID = PRESET_CONFIGS[0]?.id || null;

export function getPresetConfig(id) {
  if (!id) return null;
  return PRESET_CONFIGS.find((preset) => preset.id === id) || null;
}
